export const products = [
  {
    id: 1,
    title: "Premium Watch",
    description: "Luxury smart watch with modern features",
    price: 120,
    oldPrice: 180,
    rating: 4.5,
    image: "/products/p1.jpg",
  },
  {
    id: 2,
    title: "Headphone Pro",
    description: "Noise cancellation premium headphone",
    price: 90,
    oldPrice: 140,
    rating: 4,
    image: "/products/p2.jpg",
  },
  {
    id: 3,
    title: "Gaming Mouse",
    description: "RGB Gaming Mouse High Precision",
    price: 60,
    oldPrice: 100,
    rating: 5,
    image: "/products/p3.jpg",
  },
  {
    id: 4,
    title: "Smart Speaker",
    description: "AI Smart Speaker Voice Control",
    price: 150,
    oldPrice: 200,
    rating: 4.8,
    image: "/products/p4.jpg",
  },
  {
    id: 5,
    title: "Laptop Bag",
    description: "Premium waterproof bag",
    price: 45,
    oldPrice: 70,
    rating: 4.2,
    image: "/products/p5.jpg",
  },
  {
    id: 6,
    title: "Apple Smart Watch",
    description: "Premium health tracking smart watch",
    price: 220,
    oldPrice: 280,
    rating: 4.8,
    image: "/products/watch1.jpg",
  },
  {
    id: 7,
    title: "Nike Running Shoes",
    description: "Comfortable sports running shoes",
    price: 140,
    oldPrice: 190,
    rating: 4.6,
    image: "/products/shoe1.jpg",
  },
  {
    id: 8,
    title: "Gaming Headset",
    description: "Surround sound gaming headset",
    price: 95,
    oldPrice: 130,
    rating: 4.7,
    image: "/products/headset1.jpg",
  },
  {
    id: 9,
    title: "Wireless Keyboard",
    description: "Ultra slim wireless keyboard",
    price: 75,
    oldPrice: 110,
    rating: 4.3,
    image: "/products/keyboard1.jpg",
  },
  {
    id: 10,
    title: "Leather Wallet",
    description: "Premium leather wallet",
    price: 40,
    oldPrice: 60,
    rating: 4.1,
    image: "/products/wallet1.jpg",
  },
  {
    id: 11,
    title: "Bluetooth Speaker",
    description: "Portable mini Bluetooth speaker",
    price: 85,
    oldPrice: 120,
    rating: 4.5,
    image: "/products/speaker1.jpg",
  },
  {
    id: 12,
    title: "Men's T-Shirt",
    description: "Cotton premium t-shirt",
    price: 30,
    oldPrice: 50,
    rating: 4.2,
    image: "/products/tshirt1.jpg",
  },
  {
    id: 13,
    title: "Smart Phone Case",
    description: "Shockproof mobile case",
    price: 20,
    oldPrice: 35,
    rating: 4.4,
    image: "/products/case1.jpg",
  },
  {
    id: 14,
    title: "Laptop Cooling Pad",
    description: "High speed cooling fan pad",
    price: 15,
    oldPrice: 80,
    rating: 4.6,
    image: "/products/coolpad1.jpg",
  },
  {
    id: 16,
    title: "Gaming Mouse RGB",
    description: "RGB gaming precision mouse",
    price: 65,
    oldPrice: 95,
    rating: 4.9,
    image: "/products/mouse1.jpg",
  },
];
